/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceSourceMapRouteImport } from './routes/reference/source-map'
import { Route as ReferenceLaneConstantsRouteImport } from './routes/reference/lane-constants'
import { Route as ReferenceFiberFieldsRouteImport } from './routes/reference/fiber-fields'
import { Route as LearnReadingOrderRouteImport } from './routes/learn/reading-order'
import { Route as LearnOverviewRouteImport } from './routes/learn/overview'
import { Route as Learn06SuspenseRetryRouteImport } from './routes/learn/06-suspense-retry'
import { Route as Learn05LanesSchedulerRouteImport } from './routes/learn/05-lanes-scheduler'
import { Route as Learn04SetstateTraceRouteImport } from './routes/learn/04-setstate-trace'
import { Route as Learn03DualTreeRouteImport } from './routes/learn/03-dual-tree'
import { Route as Learn02FiberNodeRouteImport } from './routes/learn/02-fiber-node'
import { Route as Learn01WhyFiberRouteImport } from './routes/learn/01-why-fiber'

const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/diagrams.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSourceMapRoute = ReferenceSourceMapRouteImport.update({
  id: '/source-map',
  path: '/source-map',
  getParentRoute: () => ReferenceRoute,
} as any).lazy(() =>
  import('./routes/reference/source-map.lazy').then((d) => d.Route),
)
const ReferenceLaneConstantsRoute = ReferenceLaneConstantsRouteImport.update({
  id: '/lane-constants',
  path: '/lane-constants',
  getParentRoute: () => ReferenceRoute,
} as any).lazy(() =>
  import('./routes/reference/lane-constants.lazy').then((d) => d.Route),
)
const ReferenceFiberFieldsRoute = ReferenceFiberFieldsRouteImport.update({
  id: '/fiber-fields',
  path: '/fiber-fields',
  getParentRoute: () => ReferenceRoute,
} as any).lazy(() =>
  import('./routes/reference/fiber-fields.lazy').then((d) => d.Route),
)
const LearnReadingOrderRoute = LearnReadingOrderRouteImport.update({
  id: '/reading-order',
  path: '/reading-order',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/reading-order.lazy').then((d) => d.Route),
)
const LearnOverviewRoute = LearnOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/overview.lazy').then((d) => d.Route),
)
const Learn06SuspenseRetryRoute = Learn06SuspenseRetryRouteImport.update({
  id: '/06-suspense-retry',
  path: '/06-suspense-retry',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/06-suspense-retry.lazy').then((d) => d.Route),
)
const Learn05LanesSchedulerRoute = Learn05LanesSchedulerRouteImport.update({
  id: '/05-lanes-scheduler',
  path: '/05-lanes-scheduler',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/05-lanes-scheduler.lazy').then((d) => d.Route),
)
const Learn04SetstateTraceRoute = Learn04SetstateTraceRouteImport.update({
  id: '/04-setstate-trace',
  path: '/04-setstate-trace',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/04-setstate-trace.lazy').then((d) => d.Route),
)
const Learn03DualTreeRoute = Learn03DualTreeRouteImport.update({
  id: '/03-dual-tree',
  path: '/03-dual-tree',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/03-dual-tree.lazy').then((d) => d.Route),
)
const Learn02FiberNodeRoute = Learn02FiberNodeRouteImport.update({
  id: '/02-fiber-node',
  path: '/02-fiber-node',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/02-fiber-node.lazy').then((d) => d.Route),
)
const Learn01WhyFiberRoute = Learn01WhyFiberRouteImport.update({
  id: '/01-why-fiber',
  path: '/01-why-fiber',
  getParentRoute: () => LearnRoute,
} as any).lazy(() =>
  import('./routes/learn/01-why-fiber.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/learn': typeof LearnRouteWithChildren
  '/reference': typeof ReferenceRouteWithChildren
  '/learn/01-why-fiber': typeof Learn01WhyFiberRoute
  '/learn/02-fiber-node': typeof Learn02FiberNodeRoute
  '/learn/03-dual-tree': typeof Learn03DualTreeRoute
  '/learn/04-setstate-trace': typeof Learn04SetstateTraceRoute
  '/learn/05-lanes-scheduler': typeof Learn05LanesSchedulerRoute
  '/learn/06-suspense-retry': typeof Learn06SuspenseRetryRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/learn/reading-order': typeof LearnReadingOrderRoute
  '/reference/fiber-fields': typeof ReferenceFiberFieldsRoute
  '/reference/lane-constants': typeof ReferenceLaneConstantsRoute
  '/reference/source-map': typeof ReferenceSourceMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/learn': typeof LearnRouteWithChildren
  '/reference': typeof ReferenceRouteWithChildren
  '/learn/01-why-fiber': typeof Learn01WhyFiberRoute
  '/learn/02-fiber-node': typeof Learn02FiberNodeRoute
  '/learn/03-dual-tree': typeof Learn03DualTreeRoute
  '/learn/04-setstate-trace': typeof Learn04SetstateTraceRoute
  '/learn/05-lanes-scheduler': typeof Learn05LanesSchedulerRoute
  '/learn/06-suspense-retry': typeof Learn06SuspenseRetryRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/learn/reading-order': typeof LearnReadingOrderRoute
  '/reference/fiber-fields': typeof ReferenceFiberFieldsRoute
  '/reference/lane-constants': typeof ReferenceLaneConstantsRoute
  '/reference/source-map': typeof ReferenceSourceMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagrams': typeof DiagramsRoute
  '/learn': typeof LearnRouteWithChildren
  '/reference': typeof ReferenceRouteWithChildren
  '/learn/01-why-fiber': typeof Learn01WhyFiberRoute
  '/learn/02-fiber-node': typeof Learn02FiberNodeRoute
  '/learn/03-dual-tree': typeof Learn03DualTreeRoute
  '/learn/04-setstate-trace': typeof Learn04SetstateTraceRoute
  '/learn/05-lanes-scheduler': typeof Learn05LanesSchedulerRoute
  '/learn/06-suspense-retry': typeof Learn06SuspenseRetryRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/learn/reading-order': typeof LearnReadingOrderRoute
  '/reference/fiber-fields': typeof ReferenceFiberFieldsRoute
  '/reference/lane-constants': typeof ReferenceLaneConstantsRoute
  '/reference/source-map': typeof ReferenceSourceMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagrams'
    | '/learn'
    | '/reference'
    | '/learn/01-why-fiber'
    | '/learn/02-fiber-node'
    | '/learn/03-dual-tree'
    | '/learn/04-setstate-trace'
    | '/learn/05-lanes-scheduler'
    | '/learn/06-suspense-retry'
    | '/learn/overview'
    | '/learn/reading-order'
    | '/reference/fiber-fields'
    | '/reference/lane-constants'
    | '/reference/source-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagrams'
    | '/learn'
    | '/reference'
    | '/learn/01-why-fiber'
    | '/learn/02-fiber-node'
    | '/learn/03-dual-tree'
    | '/learn/04-setstate-trace'
    | '/learn/05-lanes-scheduler'
    | '/learn/06-suspense-retry'
    | '/learn/overview'
    | '/learn/reading-order'
    | '/reference/fiber-fields'
    | '/reference/lane-constants'
    | '/reference/source-map'
  id:
    | '__root__'
    | '/'
    | '/diagrams'
    | '/learn'
    | '/reference'
    | '/learn/01-why-fiber'
    | '/learn/02-fiber-node'
    | '/learn/03-dual-tree'
    | '/learn/04-setstate-trace'
    | '/learn/05-lanes-scheduler'
    | '/learn/06-suspense-retry'
    | '/learn/overview'
    | '/learn/reading-order'
    | '/reference/fiber-fields'
    | '/reference/lane-constants'
    | '/reference/source-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramsRoute: typeof DiagramsRoute
  LearnRoute: typeof LearnRouteWithChildren
  ReferenceRoute: typeof ReferenceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/source-map': {
      id: '/reference/source-map'
      path: '/source-map'
      fullPath: '/reference/source-map'
      preLoaderRoute: typeof ReferenceSourceMapRouteImport
      parentRoute: typeof ReferenceRoute
    }
    '/reference/lane-constants': {
      id: '/reference/lane-constants'
      path: '/lane-constants'
      fullPath: '/reference/lane-constants'
      preLoaderRoute: typeof ReferenceLaneConstantsRouteImport
      parentRoute: typeof ReferenceRoute
    }
    '/reference/fiber-fields': {
      id: '/reference/fiber-fields'
      path: '/fiber-fields'
      fullPath: '/reference/fiber-fields'
      preLoaderRoute: typeof ReferenceFiberFieldsRouteImport
      parentRoute: typeof ReferenceRoute
    }
    '/learn/reading-order': {
      id: '/learn/reading-order'
      path: '/reading-order'
      fullPath: '/learn/reading-order'
      preLoaderRoute: typeof LearnReadingOrderRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/overview': {
      id: '/learn/overview'
      path: '/overview'
      fullPath: '/learn/overview'
      preLoaderRoute: typeof LearnOverviewRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/06-suspense-retry': {
      id: '/learn/06-suspense-retry'
      path: '/06-suspense-retry'
      fullPath: '/learn/06-suspense-retry'
      preLoaderRoute: typeof Learn06SuspenseRetryRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/05-lanes-scheduler': {
      id: '/learn/05-lanes-scheduler'
      path: '/05-lanes-scheduler'
      fullPath: '/learn/05-lanes-scheduler'
      preLoaderRoute: typeof Learn05LanesSchedulerRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/04-setstate-trace': {
      id: '/learn/04-setstate-trace'
      path: '/04-setstate-trace'
      fullPath: '/learn/04-setstate-trace'
      preLoaderRoute: typeof Learn04SetstateTraceRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/03-dual-tree': {
      id: '/learn/03-dual-tree'
      path: '/03-dual-tree'
      fullPath: '/learn/03-dual-tree'
      preLoaderRoute: typeof Learn03DualTreeRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/02-fiber-node': {
      id: '/learn/02-fiber-node'
      path: '/02-fiber-node'
      fullPath: '/learn/02-fiber-node'
      preLoaderRoute: typeof Learn02FiberNodeRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/01-why-fiber': {
      id: '/learn/01-why-fiber'
      path: '/01-why-fiber'
      fullPath: '/learn/01-why-fiber'
      preLoaderRoute: typeof Learn01WhyFiberRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  Learn01WhyFiberRoute: typeof Learn01WhyFiberRoute
  Learn02FiberNodeRoute: typeof Learn02FiberNodeRoute
  Learn03DualTreeRoute: typeof Learn03DualTreeRoute
  Learn04SetstateTraceRoute: typeof Learn04SetstateTraceRoute
  Learn05LanesSchedulerRoute: typeof Learn05LanesSchedulerRoute
  Learn06SuspenseRetryRoute: typeof Learn06SuspenseRetryRoute
  LearnOverviewRoute: typeof LearnOverviewRoute
  LearnReadingOrderRoute: typeof LearnReadingOrderRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  Learn01WhyFiberRoute: Learn01WhyFiberRoute,
  Learn02FiberNodeRoute: Learn02FiberNodeRoute,
  Learn03DualTreeRoute: Learn03DualTreeRoute,
  Learn04SetstateTraceRoute: Learn04SetstateTraceRoute,
  Learn05LanesSchedulerRoute: Learn05LanesSchedulerRoute,
  Learn06SuspenseRetryRoute: Learn06SuspenseRetryRoute,
  LearnOverviewRoute: LearnOverviewRoute,
  LearnReadingOrderRoute: LearnReadingOrderRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ReferenceRouteChildren {
  ReferenceFiberFieldsRoute: typeof ReferenceFiberFieldsRoute
  ReferenceLaneConstantsRoute: typeof ReferenceLaneConstantsRoute
  ReferenceSourceMapRoute: typeof ReferenceSourceMapRoute
}

const ReferenceRouteChildren: ReferenceRouteChildren = {
  ReferenceFiberFieldsRoute: ReferenceFiberFieldsRoute,
  ReferenceLaneConstantsRoute: ReferenceLaneConstantsRoute,
  ReferenceSourceMapRoute: ReferenceSourceMapRoute,
}

const ReferenceRouteWithChildren = ReferenceRoute._addFileChildren(
  ReferenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramsRoute: DiagramsRoute,
  LearnRoute: LearnRouteWithChildren,
  ReferenceRoute: ReferenceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
